// <auto-generated />
using System;
using Contact_Book_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contact_Book_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607170656_AddedSeedingData")]
    partial class AddedSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contact_Book_App.Models.ContactEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Generated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ams4@gmail.com",
                            FirstName = "Amjad",
                            Generated = new DateTime(2025, 6, 7, 18, 6, 51, 518, DateTimeKind.Local).AddTicks(4289),
                            LastName = "Mustafa",
                            PhoneNumber = "048917387135"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lY6@gmail.com",
                            FirstName = "Lamine",
                            Generated = new DateTime(2025, 6, 7, 18, 6, 51, 518, DateTimeKind.Local).AddTicks(4821),
                            LastName = "Yamal",
                            PhoneNumber = "123456789014"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
